apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cassandra-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cassandra-web.name" . }}
    helm.sh/chart: {{ include "cassandra-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cassandra-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cassandra-web.name" . }}
        version: {{ .Values.image.tag }}
        app.kubernetes.io/name: {{ include "cassandra-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: HOST_PORT
            value: ":{{ .Values.service.targetPort }}"
          - name: CASSANDRA_HOST
            value: {{ .Values.db.host }}
          - name: CASSANDRA_PORT
            value: "{{ .Values.db.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
